version: '3.8'
services:
  nestjs:
    build:
      context: ./api
      dockerfile: Dockerfile
    image: eingressnest
    container_name: nestjs
    ports:
      - "3000:3000"
    networks:
      - my-network

  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: eingressangular
    container_name: angular
    ports:
      - "8080:80"  # Change host port to 8080
    depends_on:
      - nestjs
    networks:
      - my-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nestjs
      - angular
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
