version: '3.8'
services:
  nestjs:
    build:
        context: ./api
        dockerfile: Dockerfile
    image: eingressnest
    container_name: nestjs
    ports:
      - "3000:3000"

  angular:
    build:
      context: .
      dockerfile: Dockerfile
    image: eingressangular
    container_name: angular
    ports:
      - "4200:80"  # Map container port 80 to host port 4200
    depends_on:
      - nestjs
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
