name: Build and deploy Node.js app to Azure Web App - eingress

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Install dependencies, build, and test
        run: |
          npm install
          npm run build --if-present
        # npm run test --if-present

      - name: Build Angular Docker image
        run: |
          docker build -t yourdockerregistry.azurecr.io/yourimage-angular:latest -f Dockerfile .
        
      - name: Build NestJS Docker image
        run: |
          docker build -t yourdockerregistry.azurecr.io/yourimage-nestjs:latest -f api/Dockerfile ./api
        
      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.AZURE_ACR_PASSWORD }} | docker login yourdockerregistry.azurecr.io -u ${{ secrets.AZURE_ACR_USERNAME }} --password-stdin
        
      - name: Push Angular Docker image to Azure Container Registry
        run: |
          docker push yourdockerregistry.azurecr.io/yourimage-angular:latest

      - name: Push NestJS Docker image to Azure Container Registry
        run: |
          docker push yourdockerregistry.azurecr.io/yourimage-nestjs:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9EC587870DA491E954BFC77FF2C8C3F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2BF076C991743EB96DC8468A39AE641 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7E4A69CC57634119A85CC92BC032B53C }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eingress'
          slot-name: 'Production'
          package: ./deployment.zip
