name: Build and deploy Node.js app to Azure Web App - eingress

on:
  push:
    branches:
      - Development
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Angular Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/eingressangular:latest -f Dockerfile.angular .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eingressangular:latest

      - name: Build and push NestJS Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/eingressnest:latest -f Dockerfile.nest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/eingressnest:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F9EC587870DA491E954BFC77FF2C8C3F }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D2BF076C991743EB96DC8468A39AE641 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7E4A69CC57634119A85CC92BC032B53C }}

      - name: Deploy Angular and NestJS Docker images to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'eingress'
          slot-name: 'Production'
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/eingressangular:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/eingressnest:latest
